### ISSUE TITLE
Object creation fails if the content size is greater than the limit

### ISSUE THREAD

**Issue by d1snin** [hole-project/hole#5]
It can be solved by using buffered streams and disabling the limit.

```yaml
servlet:
  multipart:
    max-file-size: -1
    max-request-size: -1
```
This task is already in progress.
